# Generated by Django 5.1.3 on 2024-11-23 17:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Blog Posts Index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('sub_headline', 1), ('single_image', 4), ('multi_image', 7), ('text_content', 9), ('children_list', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('headline', 0)]], {}), 2: ('home.tools.APIImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('description', 3)]], {}), 5: ('home.tools.APIImageChooserBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'max': 4, 'min': 1, 'required': True}), 7: ('wagtail.blocks.StreamBlock', [[('images', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('content', 8)]], {}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 10, 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('folder', 10), ('limit', 11)]], {})})),
            ],
            options={
                'verbose_name': 'Flex Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FlexPagesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Blog Posts Index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('abstract', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('sub_headline', 1), ('single_image', 4), ('multi_image', 7), ('text_content', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('headline', 0)]], {}), 2: ('home.tools.APIImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('description', 3)]], {}), 5: ('home.tools.APIImageChooserBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'max': 4, 'min': 1, 'required': True}), 7: ('wagtail.blocks.StreamBlock', [[('images', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('content', 8)]], {})})),
                ('link_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog Post',
            },
            bases=('wagtailcore.page',),
        ),
    ]
