# Generated by Django 5.1.3 on 2024-11-23 17:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpagesindexpage',
            options={'verbose_name': 'Flex Pages Index'},
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='body',
            field=wagtail.fields.StreamField([('sub_headline', 1), ('single_image', 4), ('multi_image', 7), ('text_content', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('headline', 0)]], {}), 2: ('home.tools.APIImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('description', 3)]], {}), 5: ('home.tools.APIImageChooserBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'max': 4, 'min': 1, 'required': True}), 7: ('wagtail.blocks.StreamBlock', [[('images', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('content', 8)]], {})}),
        ),
    ]
